---
- name: confirm redhat lsb util is present pre2.8.0
  yum:
    name: redhat-lsb-core
    state: present
  when: nrinfragent_os_name == 'redhat' and ansible_version.full < "2.8.0"

- name: confirm redhat lsb util is present post2.8.0
  yum:
    name: redhat-lsb-core
    state: present
    lock_timeout: "{{ nrinfragent_yum_lock_timeout }}"
  when: nrinfragent_os_name == 'redhat' and ansible_version.full >= "2.8.0"

- name: reread ansible_lsb facts
  setup:
    filter: ansible_lsb*
  when: nrinfragent_os_name == 'redhat'

- name: setup agent repo keys
  apt_key:
    url: https://download.newrelic.com/infrastructure_agent/keys/newrelic_apt_key_current.gpg
    state: present
  when: nrinfragent_os_name == 'debian'

- name: setup agent repo keys
  rpm_key:
    key: https://download.newrelic.com/infrastructure_agent/keys/newrelic_rpm_key_current.gpg
    state: present
  when: nrinfragent_os_name == 'redhat'

- name: setup agent repo keys
  rpm_key:
    key: https://download.newrelic.com/infrastructure_agent/keys/newrelic_rpm_key_current.gpg
    state: present
  when: nrinfragent_os_name == 'suse'

- name: confirm Debian apt-transport-https is present
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes
  when: nrinfragent_os_name == 'debian'

- name: setup agent repo reference
  apt_repository:
    repo: "deb https://download.newrelic.com/infrastructure_agent/linux/apt {{ nrinfragent_os_codename }} main"
    state: present
    update_cache: "yes"
  when: nrinfragent_os_name == 'debian'

- name: setup agent repo reference
  yum_repository:
    baseurl: "https://download.newrelic.com/infrastructure_agent/linux/yum/el/{{ (ansible_service_mgr == 'upstart') | ternary('6', '7') }}/{{ ansible_architecture }}"
    gpgcheck: "yes"
    gpgkey: https://download.newrelic.com/infrastructure_agent/keys/newrelic_rpm_key_current.gpg
    name: 'newrelic-infra'
    repo_gpgcheck: 'yes'
    state: present
    description: New Relic Infrastructure
  when: nrinfragent_distribution == 'amazon'
  register: setup_agent_repo_amazon

- name: setup agent repo reference
  yum_repository:
    baseurl: "https://download.newrelic.com/infrastructure_agent/linux/yum/el/{{ nrinfragent_os_version }}/{{ ansible_architecture }}"
    gpgcheck: "yes"
    gpgkey: https://download.newrelic.com/infrastructure_agent/keys/newrelic_rpm_key_current.gpg
    name: 'newrelic-infra'
    repo_gpgcheck: "{{ (nrinfragent_os_version == '5') | ternary('no', 'yes') }}"
    state: present
    description: New Relic Infrastructure
  when: nrinfragent_os_name == 'redhat' and ansible_distribution|lower != 'amazon'
  register: setup_agent_repo_redhat

- name: setup agent repo reference
  zypper_repository:
    name: newrelic-infra
    description: New Relic Infrastructure Agent
    repo: "http://download.newrelic.com/infrastructure_agent/linux/zypp/sles/{{ ansible_distribution_version }}/{{ ansible_machine }}/"
    runrefresh: "yes"
    auto_import_keys: "yes"
    disable_gpg_check: "yes"
  when: nrinfragent_os_name == 'suse'
  register: infra_agent_zypper_repo

- name: run make cache to actually import gpg key
  command: "yum -q makecache -y --disablerepo='*' --enablerepo='newrelic-infra'"
  when: nrinfragent_os_name == 'redhat' and (setup_agent_repo_amazon.changed or setup_agent_repo_redhat.changed)
  tags:
    - skip_ansible_lint
  args:
    warn: false

- name: create log destination directory
  file:
    path: "{{ nrinfragent_config['log_file'] | dirname }}"
    state: directory
    recurse: true
  when:
    - nrinfragent_state != 'absent'
    - nrinfragent_config['log_file'] is defined

- name: install agent pre2.8.0
  package:
    name: "newrelic-infra"
    state: "{{ nrinfragent_state }}"
  when: nrinfragent_os_name != 'windows' and ansible_version.full < "2.8.0"

- name: install agent post2.8.0
  package:
    name: "newrelic-infra"
    state: "{{ nrinfragent_state }}"
  when: nrinfragent_os_name != 'windows' and ansible_version.full >= "2.8.0" and nrinfragent_os_name != 'amazon' and nrinfragent_os_name != 'redhat'

- name: Install agent yum
  yum:
    name: "newrelic-infra"
    state: "{{ nrinfragent_state }}"
    lock_timeout: "{{ nrinfragent_yum_lock_timeout }}"
  when: (nrinfragent_os_name == 'redhat' or nrinfragent_os_name == 'amazon') and ansible_version.full >= "2.8.0"

- name: install integrations pre2.8.0
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ nrinfragent_integrations }}"
  when: nrinfragent_os_name != 'windows' and ansible_version.full < "2.8.0"

- name: Install integrations post2.8.0
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ nrinfragent_integrations }}"
  when: nrinfragent_os_name != 'windows' and ansible_version.full >= "2.8.0" and nrinfragent_os_name != 'amazon' and nrinfragent_os_name != 'redhat'

- name: Install integrations yum
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    lock_timeout: "{{ nrinfragent_yum_lock_timeout }}"
  with_items: "{{ nrinfragent_integrations }}"
  when: nrinfragent_os_name == 'redhat' or nrinfragent_os_name == 'amazon' and ansible_version.full >= "2.8.0"

- name: install agent (windows)
  win_chocolatey:
    name: newrelic-infra
    state: "{{ nrinfragent_state }}"
    version: "{{ nrinfragent_choco_version | default(omit) }}"
  when:
    - nrinfragent_os_name == 'windows'
